[package]
name = "mcnotify"
version = "0.1.0"
authors = ["Shusui MOYATANI <syusui.s@gmail.com>"]

[dependencies]
byteorder = "1.0.0"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
xdg-basedir = "1.0.0"
toml = "0.4.2"
getopts = "0.2"
strfmt = "0.1.5"
chrono = "0.4.0"
egg-mode = "0.9.0"
