name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: ./.github/actions/cache
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - name: Format
        run: cargo fmt --all -- --check
      # TODO: enable clippy
      # - name: Lint
      #   run: cargo clippy
      - name: Test
        run: cargo test --all
      - name: Build
        run: cargo build
      - name: Run
        run: cargo run -- --version
