name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('rust-toolchain@') }}
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - name: Format
        run: cargo fmt --all -- --check
      # TODO: enable clippy
      # - name: Lint
      #   run: cargo clippy
      - name: Test
        run: cargo test --all
      - name: Build
        run: cargo build
      - name: Run
        run: cargo run -- --version
