name: Release
on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - run: mkdir binaries
      - name: x86_64-unknown-linux-gnu
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo clean
          export RUSTFLAGS="-C strip=symbols --remap-path-prefix=$(pwd)=. --remap-path-prefix=$(cd; pwd)=/home/rust/"
          cargo build --release
          cp target/release/mcnotify binaries/mcnotify.x86_64-unknown-linux-gnu
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/mcnotify.x86_64-unknown-linux-gnu
